name: Deploy for Android

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-android:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./Abacus


      - name: Decode Keystore & Save to File
        shell: bash
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > ./Abacus/abacus.keystore
          
      - name: List Files for Debugging
        run: dir ./Abacus

      - name: Build Signed APK
        run: dotnet publish ./Abacus/Abacus.csproj -c Release -f net10.0-android -p:AndroidPackageFormat=apk -p:AndroidSigningKeyStore=./Abacus/abacus.keystore -p:AndroidSigningKeyAlias=${{ secrets.SIGNING_KEY_ALIAS }} -p:AndroidSigningKeyPass=${{ secrets.SIGNING_KEY_PASSWORD }} -p:AndroidSigningStorePass=${{ secrets.SIGNING_KEYSTORE_PASSWORD }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ./Abacus/bin/Release/net10.0-android/*.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extractVersion.outputs.version }}
          name: Release v${{ steps.extractVersion.outputs.version }}
          body: |
            Signed Android APK for version ${{ steps.extractVersion.outputs.version }}.
          files: ./Abacus/bin/Release/net10.0-android/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


