name: Deploy for Android

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-android:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./Abacus

      - name: Build Android APK
        run: dotnet build ./Abacus/Abacus.csproj -c Release -f net10.0-android

      - name: Publish APK
        run: dotnet publish ./Abacus/Abacus.csproj -c Release -f net10.0-android -o ./Abacus/bin/Release/net10.0-android/AppPackages

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: ./Abacus/bin/Release/net10.0-android/AppPackages/*.apk
