name: Generate Android Keystore

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Generate Keystore
        shell: pwsh
        run: |
          keytool -genkeypair `
            -keystore Abacus/abacus.keystore `
            -alias abacus-key `
            -keyalg RSA `
            -keysize 2048 `
            -validity 10000 `
            -storepass "${{ secrets.SIGNING_KEY_PASSWORD }}" `
            -keypass "${{ secrets.SIGNING_KEY_PASSWORD }}" `
            -dname "CN=Abacus, OU=DevOps, O=MyCompany, L=Dhaka, S=Dhaka, C=BD"
      
          if (!(Test-Path "Abacus/abacus.keystore")) {
            Write-Error "Keystore creation failed!"
          }

      - name: Convert Keystore to Base64
        shell: pwsh
        run: |
          $bytes = [System.IO.File]::ReadAllBytes("Abacus/abacus.keystore")
          $base64 = [Convert]::ToBase64String($bytes)

          Write-Output ""
          Write-Output "================ COPY THIS VALUE ================"
          Write-Output $base64
          Write-Output "================================================"
